name: Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  SKIP_SLOW_TESTS: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Puzzles
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: latest
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
